version: "3.8"
services:
  api_service:
    build:
      context: api/.
      args:
        PYTHON_VERSION: "3.12"
        PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - PORT=${API_PORT:-8000}
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./api:/app # Mount the local 'api' directory to '/app' in the container

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  telegram_bot:
    build:
      context: ./telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TG_BOT_TOKEN}
      - API_PORT=${API_PORT:-8000}
    restart: unless-stopped
    depends_on:
      - api_service
    volumes:
    - ./telegram_bot:/app # Mount the local 'api' directory to '/app' in the container

volumes:
  postgres_data:
