version: "3.8"
services:
  api_service:
    build:
      context: api/.
      args:
        PYTHON_VERSION: "3.12"
        PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - PORT=${API_PORT:-8000}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  telegram_bot:
    build:
      context: ./telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_PORT=${API_PORT:-8000}
    restart: unless-stopped
    depends_on:
      - api_service

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"  # Expose pgAdmin on port 5050 of the host
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
